### ISSUE TITLE
请问在 搜题 接口可不可以加个请求参数？

### ISSUE THREAD

**Issue by xdingya** [zmide/study.zmide.com#12]
请问在 搜题 接口可不可以加个 确定用户身份 的请求参数？
因为有些题目可能题干相似，导致每次搜到的答案都不是我上传的题目的。
或者确定一个搜题优先级，优先搜索自己上传的题库，再查找公共题库。

**Comment by PBK-B** [comment]
感谢反馈，由于现在搜索做了分词处理，可能会导致因为其他题干分词的权重比较高出现这种情况，在用登录的情况下优先搜索用户自己的题库是个非常好的建议
@JessieChan0730 你有空看看这个需求，在后端接口上处理一下？
