### ISSUE TITLE
为什么我注册账号后提示密码错误

### ISSUE THREAD

**Issue by maidang2233** [zmide/study.zmide.com#8]
为什么我注册账号后提示密码错误

**Comment by PBK-B** [comment]
@maidang2233 是不是在注册或者登录的时候大小写错误了？

**Comment by PBK-B** [comment]
目前感觉这块有功能缺失，按道理应该需要找回密码和确认密码功能

- 注册时，需要二次输入确认密码
- 实现通过邮箱验证码找回密码

**Comment by PBK-B** [comment]
[需求] 注册时，需要二次输入确认密码，在注册账号时需要用户再次输入密码，前端效验两次输入密码是否相同

![50e84eb09661817c3e97514cbf0463f0](https://github.com/zmide/study.zmide.com/assets/39079814/d47747a0-d05b-4c1d-a05e-bbc378bb7da7)

**Comment by PBK-B** [comment]
[需求] 实现通过邮箱验证码找回密码，这里需要 @PBK-B 提供发送找回密码验证码接口，实现通过邮箱地址，获取验证码，填写新密码完成密码修改（同样需要确认密码输入框）

![d25213744f9e8cace9562680134a1c7f](https://github.com/zmide/study.zmide.com/assets/39079814/c6970288-d89e-46c4-8eeb-61fcd57d8d7d)

**Comment by maidang2233** [comment]
视频发不了，太大了，大概内容是我用126的邮箱注册了个账号，密码为123456，但我点确定登录时在登录页面却显示了一段比较长的密码，当我用开发者选项显示密码时里面的内容显示的是我的126账号，却不是密码，但我输入123456时显示密码错误，我输入邮箱的时候也是密码错误
我在注册时没有看到再次输入密码的选项

**Comment by PBK-B** [comment]
> 视频发不了，太大了，大概内容是我用126的邮箱注册了个账号，密码为123456，但我点确定登录时在登录页面却显示了一段比较长的密码，当我用开发者选项显示密码时里面的内容显示的是我的126账号，却不是密码，但我输入123456时显示密码错误，我输入邮箱的时候也是密码错误 我在注册时没有看到再次输入密码的选项

@maidang2233 目前这些代码还没上线，等这边找回密码功能合并之后会上线确认密码和找回密码功能
